
#include "Containers/Array.h"
#include "log.h"
#include <SFML/Graphics.hpp>
#include <imgui-SFML.h>
#include <imgui.h>

#include <Entities.h>
#include <iostream>
#include <utility.h>
#include <vector>

int main()
{
	container::Array<bool, 3> arr;

	auto window = sf::RenderWindow(sf::VideoMode({ 1920u, 1080u }), "Fake Mario");
	window.setFramerateLimit(144);
	if (!ImGui::SFML::Init(window))
		return -1;

	sf::Clock clock;
	while (window.isOpen())
	{
		while (const std::optional event = window.pollEvent())
		{
			ImGui::SFML::ProcessEvent(window, *event);

			if (event->is<sf::Event::Closed>())
			{
				window.close();
			}
		}// end user input loop

		ImGui::SFML::Update(window, clock.restart());

		ImGui::Begin("sdfkjasbdf");
		ImGui::End();
		window.clear();
		ImGui::SFML::Render(window);
		window.display();
	}

	ImGui::SFML::Shutdown();
	
}